[tool.poetry]
name = "monte-carlo-execrcise"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = [{include = "monte_carlo_execrcise"}]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.3"
pandas = "^2.0.1"


[tool.poetry.group.dev.dependencies]
pycodestyle = "^2.10.0"
isort = "^5.12.0"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
